### PR TITLE
Fix validator registration retry

### LINKED ISSUE #9850: Builder not available: several registrations attempts in a row
Image

apparently we try and print a lot of
```
2025-09-04 20:04:48.710 INFO  - Validator   *** 0 out of 8 validator registration(s) were successfully sent to the builder network via the Beacon Node.
2025-09-04 20:04:48.710 ERROR - Validator   *** Failed to send validator registrations to the builder network via the Beacon Node
```

despite we say we will retry in 30s, we do it immediately?

[registration.log](https://github.com/user-attachments/files/22146818/registration.log)

### PR DESCRIPTION
**Pull request by tbenr**
moves `registrationInProgress` check at the top of the process.

added a test triggering the issue.

fixes #9850

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorRegistrator.java [hunk 1]
```diff
@@ -174,11 +180,15 @@ public void onUpdatedValidatorStatuses(
...
             })
         .finish(
+            __ -> registrationInProgress.set(false),
             error -> {
               VALIDATOR_LOGGER.registeringValidatorsFailed(error);
               LOG.info("Will retry to register validators in {} seconds", RETRY_DELAY.toSeconds());
               asyncRunner.runAfterDelay(
-                  () -> onUpdatedValidatorStatuses(newValidatorStatuses, possibleMissingEvents),
+                  () -> {
+                    registrationInProgress.set(false);
```
Comment (StefanBratanov) [inline validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorRegistrator.java:189]: Shouldn't we move this outside of the lambda?

Comment (tbenr) [reply validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorRegistrator.java:189]: i don't think so. I wanted to keep the gate closed and reopen it just before calling the function again

Comment (tbenr) [reply validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorRegistrator.java:189]: essentially the delayed "retry" is still considered "registrationInProgress"

Comment (StefanBratanov) [reply validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorRegistrator.java:189]: I get it, think it makes sense

**Review by StefanBratanov — APPROVED** [review]
LGTM
