### PR TITLE
Data unavailable block pool

### LINKED ISSUE #7112: BlobSidecar fetch retry on DATA_UNAVAILABLE
We should retry to fetch missing blobSidecars by root when we fail block import due to data unavailable

### PR DESCRIPTION
**Pull request by tbenr**
Implements a "wait more and retry" mechanism for blocks that failed to import due to data unavailability.

This behaviour is only active when the node is in "in-sync" mode.

fixes: #7112

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/blobs/DataUnavailableBlockPool.java [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+ * This pool is designed to track chain tips blocks that has been attempted to import but failed due
+ * to data unavailability. These are chain tips only because blocks with unknown parent will fail
+ * with UNKNOWN_BLOCK and will be tracked in the block pendingPool.
+ */
+public class DataUnavailableBlockPool {
+  private static final Logger LOG = LogManager.getLogger();
+
+  private static final Duration WAIT_BEFORE_RETRY = Duration.ofSeconds(1);
+
+  private final Queue<SignedBeaconBlock> awaitingDataAvailabilityQueue =
```
Comment (zilm13) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/blobs/DataUnavailableBlockPool.java:39]: Even so you've added clear class description, I'd add here something like "only fork tips here"

**Review by zilm13 — APPROVED** [review]
LGTM
