### PR TITLE
Fix pre-fulu minCustodyPeriodSlotCalculator

### LINKED ISSUE #10172: exception on pre-fulu coming from MinCustodyPeriodSlotCalculator
```
2025-11-25 12:10:00.033+10:00 | beaconchain-async-2 | ERROR | DataColumnSidecarCustodyImpl | Unexpected error while advancing first custody incomplete slot for checkpoint Checkpoint{epoch=2, root=0xd4515640459e85c0bbce43e646456a07870d2f4d6ecfcefdbc6d012ab024805a}
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.stream.AsyncIteratorCollector.onError(AsyncIteratorCollector.java:44) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.stream.AbstractDelegatingStreamHandler.onError(AbstractDelegatingStreamHandler.java:31) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.stream.AbstractDelegatingStreamHandler.onError(AbstractDelegatingStreamHandler.java:31) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.stream.MapStreamHandler.onNext(MapStreamHandler.java:33) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.stream.FutureAsyncIteratorImpl.lambda$iterate$1(FutureAsyncIteratorImpl.java:30) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$finish$39(SafeFuture.java:505) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:150) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$29(SafeFuture.java:461) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at tech.pegasys.teku.statetransition.datacolumns.MinCustodyPeriodSlotCalculator.lambda$createFromSpec$0(MinCustodyPeriodSlotCalculator.java:31) ~[teku-ethereum-statetransition-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.statetransition.datacolumns.DataColumnSidecarCustodyImpl.lambda$retrievePotentiallyIncompleteSlotCustodies$5(DataColumnSidecarCustodyImpl.java:238) ~[teku-ethereum-statetransition-develop.jar:25.11.0+53-gc325ae9c13]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at tech.pegasys.teku.statetransition.datacolumns.DataColumnSidecarCustodyImpl.lambda$retrievePotentiallyIncompleteSlotCustodies$6(DataColumnSidecarCustodyImpl.java:236) ~[teku-ethereum-statetransition-develop.jar:25.11.0+53-gc325ae9c13]
	at tech.pegasys.teku.infrastructure.async.stream.MapStreamHandler.onNext(MapStreamHandler.java:31) ~[teku-infrastructure-async-develop.jar:25.11.0+53-gc325ae9c13]
	... 19 more
```

### PR DESCRIPTION
**Pull request by tbenr**
fixes: #10172

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

---

> [!NOTE]
> Make `getMinCustodyPeriodSlot` return `Optional` (empty pre-Fulu) and update custody and sync flows to respect absent custody period with adjusted behavior and tests.
> 
> - **Core API**:
>   - Change `MinCustodyPeriodSlotCalculator#getMinCustodyPeriodSlot` to return `Optional<UInt64>`; pre-Fulu now returns empty.
>   - Update implementation in `createFromSpec` to conditionally compute/start slot; add `SpecConfigFulu` usage.
> - **Custody Logic**:
>   - `DataColumnSidecarCustodyImpl`:
>     - On custody group increase, update `firstCustodyIncompleteSlot` only if min custody period present.
>     - `retrievePotentiallyIncompleteSlotCustodies` handles empty start slot (no stream).
>     - `retrieveSlotCustody` throws if called outside custody period; otherwise keeps skip behavior when below min slot.
>   - `DasCustodySync`:
>     - Filter missing columns using `minCustodyPeriodSlotCalculator.getMinCustodyPeriodSlot(...).orElseThrow()`; skip requests outside retention.
> - **Test Fixtures**:
>   - `DasCustodyStand#getMinCustodySlot` now returns `Optional`.
> - **Tests**:
>   - Update mocks and assertions to use `Optional` for min custody slot (e.g., `DasCustodySyncTest`).
>   - Expand `DataColumnSidecarCustodyImplTest`: pre-Fulu behavior, epoch-boundary updates, exception on pre-Fulu retrieval, adjusted slots around Fulu activation.
>   - Rework `MinCustodyPeriodSlotCalculatorTest` to use real spec; add cases for clamping to Fulu activation, post-activation, exact boundary, and pre-Fulu (empty).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4a3a51d5d43cf1b3940f3429eb7557ec9e1a9ce3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ethereum/statetransition/src/test/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImplTest.java [hunk 1]
```diff
@@ -154,6 +157,7 @@ public void onSlot_checksOnEpochBoundarySlot() {
 
   @Test
   public void onNewFinalizedCheckpoint_noFinalizedColumnsAvailable() {
```
Comment (zilm13) [inline ethereum/statetransition/src/test/java/tech/pegasys/teku/statetransition/datacolumns/DataColumnSidecarCustodyImplTest.java:162]: could you please also verify that pre-fulu db.setFirstCustodyIncompleteSlot is not called when `onSlot`and when `onNewFinalizedCheckpoint`

**Review by zilm13 — APPROVED** [review]
LGTM
