### PR TITLE
Fix StatusMessageFactory::updateEarliestAvailableSlot

### LINKED ISSUE #10245: `StatusMessageFactory::updateEarliestAvailableSlot` not going earlier than DA window lower bound
https://github.com/ethereum/consensus-specs/blob/master/specs/fulu/p2p-interface.md#status-v2

in particular:
`
If the node is able to serve all sidecars throughout the entire sidecars retention period (as defined by both MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS and MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS), it should advertise the earliest slot from which it can serve all blocks.
`

we should be able to go back to earliest available block if we have custody across all DA window.

### PR DESCRIPTION
**Pull request by tbenr**
fixes #10245

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

---

> [!NOTE]
> **Medium Risk**
> Changes peer-advertised availability (`StatusMessage`) semantics under Fulu and adds conditional logic based on custody period/backfill state; incorrect calculations could impact syncing/peer interactions, though changes are localized and covered by new tests.
> 
> **Overview**
> Fixes `StatusMessageFactory.updateEarliestAvailableSlot` so `earliest_available_slot` is computed relative to the **Fulu data-column custody period** instead of always combining block and data-column availability.
> 
> It introduces a `MinCustodyPeriodSlotCalculator` dependency and new logic: while data-column backfill is incomplete (data-column earliest slot is newer than the custody boundary), advertise the max of block/data-column earliest; once backfill covers the full custody period, advertise the earliest block slot only. `MinCustodyPeriodSlotCalculator.createFromSpec` is also hardened to return empty when Fulu isn’t present in the fork schedule, and tests are expanded to cover these scenarios and injection paths.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 12f4743ec9246b765929c5a4e6e2bd9c4b358b44. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java [hunk 1]
```diff
@@ -170,30 +184,70 @@ public void earliestAvailableSlotScenarios(
 
   private static Stream<Arguments> earliestAvailableSlotScenariosParams() {
     return Stream.of(
+        // Case 1: Backfill Incomplete (dataColumn > minCustody) - returns max(block, dataColumn)
```
Comment (zilm13) [inline networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java:203]: could you duplicate here, what is arg1, arg2, arg3, arg4
maybe in javadoc?

File: networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java [hunk 2]
```diff
@@ -147,17 +149,29 @@ public void shouldUpdatedEarliestAvailableSlot() {
...
     when(combinedChainDataClient.getEarliestAvailableBlockSlot())
         .thenReturn(SafeFuture.completedFuture(blockEarliestAvailableSlot));
     when(combinedChainDataClient.getEarliestAvailableDataColumnSlotWithFallback())
-        .thenReturn(SafeFuture.completedFuture(dataColumnLatestAvailableSlot));
-    statusMessageFactory.onSlot(UInt64.ZERO);
+        .thenReturn(SafeFuture.completedFuture(dataColumnEarliestAvailableSlot));
+    factoryWithMockedCalculator.onSlot(UInt64.ZERO);
 
     if (expectedEarliestAvailableSlot.isPresent()) {
       checkStatusMessagedHasExpectedEarliestAvailableSlot(
```
Comment (zilm13) [inline networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java:180]: It's a bit confusing to see 0 in else branch as it means that everything since genesis is available, while we want to advertise an opposite. Maybe make a more complex mock, something like
```java
    when(combinedChainDataClient.getCurrentEpoch()).thenReturn(UInt64.valueOf(100));
    when(recentChainData.getFinalizedEpoch()).thenReturn(UInt64.valueOf(100));
    final UInt64 currentSlot = UInt64.valueOf(800);
....
        factoryWithMockedCalculator.onSlot(UInt64.valueOf(800));
...
checkStatusMessagedHasExpectedEarliestAvailableSlot(rpcRequestBodySelector, UInt64.valueOf(800));
```

**Review by zilm13 — APPROVED** [review]
LGTM, just nits

File: networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java (hunk 2 above)
Comment (tbenr) [reply networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/StatusMessageFactoryTest.java:180]: ye good point
