### PR TITLE
Fix inconsistency of synced custody group count

### LINKED ISSUE #10039: nodeId and column custody consistency
If user deletes the p2p private key, we will regenerate it. Than the nodeId changes and we will have a different custody column set.
We have to handle the consistency somehow.

### LINKED ISSUE #10232: Enabling `p2p-subscribe-all-custody-subnets-enabled` does not trigger backfill
We do not trigger backfill because we fail to detect the change.

In  `DasCustodyBackfiller` constructor we initialize with  the current synced custody with:

```java
this.currentSyncCustodyGroupCount = custodyGroupCountManager.getCustodyGroupSyncedCount();
```

but `custodyGroupCountManager.getCustodyGroupSyncedCount()` will return 128, which is a lie.

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
Alternative to #10396. Should fix all potential cases when synced count was incorrect.
Removed synced custody group count at all.
We used it for 2 main consumers:
- `StatusMessage`. `StatusMessage` provides both `earliestAvailableSlot` and `cgc`, so other peers should expect `cgc` custody count starting from `earliestAvailableSlot`, 
which basically means that it doesn't require full backfill since we provide correct `earliestAvailableSlot`, we should use just custody count here. 
- ENR. In spec it's not mentioned whether ENR should advertise synced or non-synced count, which means it's up to the client implementation. As far as 99% peers in network
are already synced, it makes sense to advertise non-synced number here too. In 99% cases other peers are looking for gossip source which doesn't require full backfill.

With changes in this PR Backfiller on start checks earliestAvailableSlot DB custody and compares it to the requirement to find if Backfilling is needed. This should fix also #10039

## Fixed Issue(s)

Closes #10039 
Closes #10232 

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

---

> [!NOTE]
> **Medium Risk**
> Changes DAS custody backfill and peer-advertised custody group count semantics by removing the separate "synced" count and deriving resync needs from stored sidecar data, which could affect restart/backfill behavior and network metadata/ENR updates.
> 
> **Overview**
> Removes the separate *synced/backfilled* custody group count concept across statetransition and networking, simplifying `CustodyGroupCountChannel` to a single `onGroupCountUpdate` signal and dropping synced-count metrics/logging.
> 
> Updates `DasCustodyBackfiller` restart behavior to *derive* how many custody groups are actually present by inspecting stored data column identifiers (using `earliestAvailableCustodySlot` + sidecar indices) and triggers a resync (cursor reset to current slot) when the DB is behind required custody columns or when custody requirements increase.
> 
> `MetadataMessagesFactory` (and discovery/ENR wiring) now advertises the current custody group count directly, and tests/acceptance expectations are updated accordingly; `MiscHelpersFulu` exposes `getCustodyColumnsPerGroup()` to support the new synced-count calculation.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4f4543408902e6de76c336bed3e4fe122f08c3cd. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 1]
```diff
@@ -475,6 +480,52 @@ private SafeFuture<Void> requestColumnSidecar(final DataColumnSlotAndIdentifier
...
+                      .map(DataColumnSlotAndIdentifier::columnIndex)
+                      .collect(Collectors.toSet());
+              final List<UInt64> requiredIndices =
+                  custodyGroupCountManager.getCustodyColumnIndices();
+              final Set<UInt64> missingIndices =
+                  requiredIndices.stream()
+                      .filter(index -> !availableIndices.contains(index))
+                      .collect(Collectors.toSet());
+
+              return requiredIndices.size() - missingIndices.size();
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: this is a bit mind blowing.

can we just `availableIndices.stream().filter(requiredIndices::contains).count()` ?

Comment (tbenr) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: i don't know what your logic will capture. maybe is too late here.

Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: `availableIndices.stream().filter(requiredIndices::contains).count()` and what value it represents?

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 2]
```diff
@@ -110,17 +110,27 @@ public DasCustodyBackfiller(
...
-                  Duration.ZERO,
-                  backfillCheckInterval,
-                  error -> LOG.error("Failed to run data column backfill", error)));
+      retrieveSyncedCustodyGroupCount()
+          .thenAccept(
+              syncedCount -> {
+                requiresResyncDueToCustodyGroupCountChange =
+                    syncedCount < currentSyncCustodyGroupCount;
+              })
+          .always(this::scheduleBackfiller);
```
[the remark this answers is not in the document]
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java:132]: fixed with https://github.com/Consensys/teku/pull/10401/commits/7586609c065501f483f9680d40ba8bba7b16fdbf and https://github.com/Consensys/teku/pull/10401/commits/dd0ac3e60200caab89ef831e5434fa6d63278ace

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java (hunk 1 above)
Comment (zilm13) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: Ahh we could do this, ok?
```java
              final Set<UInt64> missingIndices =
                  requiredIndices.stream()
                      .filter(index -> !availableIndices.contains(index))
                      .collect(Collectors.toSet());

              return requiredIndices.size() - missingIndices.size();
```
to
```java
              final long syncedIndicesCount =
                  requiredIndices.stream()
                      .filter(availableIndices::contains)
                      .count();

              return syncedIndicesCount;
```

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 3]
```diff
@@ -65,6 +65,7 @@ public class DasCustodyBackfiller extends Service
   private final MinCustodyPeriodSlotCalculator minCustodyPeriodSlotCalculator;
 
   private Optional<Cancellable> scheduledBackfiller = Optional.empty();
+  private boolean cancelled = false;
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: we normally use `volatile` in these cases (stop could be called by another thread)

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 4]
```diff
@@ -110,19 +111,33 @@ public DasCustodyBackfiller(
...
+            asyncRunner.runWithFixedDelay(
+                this::runBackfillCycle,
+                Duration.ZERO,
+                backfillCheckInterval,
+                error -> LOG.error("Failed to run data column backfill", error)));
+  }
+
   @Override
   protected synchronized SafeFuture<?> doStop() {
+    this.cancelled = true;
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java]: not a fan of `this.` here

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 5]
```diff
@@ -110,19 +111,33 @@ public DasCustodyBackfiller(
...
-      scheduledBackfiller =
-          Optional.of(
-              asyncRunner.runWithFixedDelay(
-                  this::runBackfillCycle,
-                  Duration.ZERO,
-                  backfillCheckInterval,
-                  error -> LOG.error("Failed to run data column backfill", error)));
+      retrieveSyncedCustodyGroupCount()
+          .thenAccept(
+              syncedCount -> {
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java:121]: you can remove `{`

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 6]
```diff
@@ -110,19 +111,33 @@ public DasCustodyBackfiller(
...
+                requiresResyncDueToCustodyGroupCountChange =
+                    syncedCount < currentSyncCustodyGroupCount;
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java:123]: I'd add log line like onGroupCountUpdate

Comment (tbenr) [reply ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java:123]: if (requiresResyncDueToCustodyGroupCountChange) {
         LOG.info("Custody group count resync needed: synced={}, required={}",
             syncedCount, currentSyncCustodyGroupCount);
     }
     
     and we could move to an info in onGroupCountUpdate too

**Review by tbenr — APPROVED** [review]
LGTM.
just some additional random nits:

### createCustodyGroupCountSyncedSubscriber
The factory method createCustodyGroupCountSyncedSubscriber (in CustodyGroupCountChannel.java:23) no longer has anything to do with "synced" count - it now just forwards the
 custodyGroupCount from onGroupCountUpdate. It should be renamed to something like createCustodyGroupCountSubscriber to reflect the new semantics.

 This is used in BeaconChainController.java:2010 where the variable is still named cgcSynced. Both the method and the variable name are now misleading.

File: ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java [hunk 7]
```diff
@@ -121,11 +121,13 @@ protected synchronized SafeFuture<?> doStart() {
...
                     syncedCount < currentSyncCustodyGroupCount;
-                LOG.info(
-                    "DasCustodyBackfiller: DB custody check reveals insufficient custody data. "
-                        + "We have {}, required {}",
-                    syncedCount,
-                    currentSyncCustodyGroupCount);
+                if (requiresResyncDueToCustodyGroupCountChange) {
+                  LOG.info(
+                      "Custody resync required: synced {} groups from DB, but {} required. "
+                          + "Backfill will restart from current slot.",
```
Comment (tbenr) [inline ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/datacolumns/DasCustodyBackfiller.java:127]: why those `+`? can you put it all in the same string (same below)
