### PR TITLE
Changed ephemery to use remote configuration

### LINKED ISSUE #9121: update ephemery teku config to pull config from internet
```
network: "https://ephemery.dev/latest/config.yaml"
```

we should be pulling network config from the internet for ephemery. When we updated it this time for electra, anyone that rebuilt was broken until the network cycled, and it'd be nice to avoid that in future.

### LINKED ISSUE #9858: ephemery testnet - unable to start
With teku 25.9.1 on ephemery testnet, teku fails during checkpoint sync.

```
teku[32194]: The fork from the initial-state (Fork{epoch=0, previous_version=0x5000101b, current_version=0x6000101b}) does not match the configured fork schedule (Fork{epoch=10, previous_version=0x5000101b, current_version=0x6000101b}).
teku[32194]: Please check that network in configuration matches the loaded state.
```

Changing checkpoint servers did not resolve this issue.

### PR DESCRIPTION
**Pull request by rolfyone**
fixes #9858
fixes #9121

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java [hunk 1]
```diff
@@ -778,7 +777,30 @@ public Builder startupTimeoutSeconds(final int startupTimeoutSeconds) {
     }
 
     public Builder discoveryBootnodes(final String... discoveryBootnodes) {
-      this.discoveryBootnodes = asList(discoveryBootnodes);
+      this.discoveryBootnodes.addAll(asList(discoveryBootnodes));
+      return this;
+    }
```
[the remark this answers is not in the document]
Comment (lucassaldanha) [reply ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:782]: It doesn't look like an issue to me.

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java [hunk 2]
```diff
@@ -778,10 +775,46 @@ public Builder startupTimeoutSeconds(final int startupTimeoutSeconds) {
...
 
     public Builder discoveryBootnodes(final String... discoveryBootnodes) {
-      this.discoveryBootnodes = asList(discoveryBootnodes);
+      for (final String bootnode : discoveryBootnodes) {
+        addBootnodeIfMissing(bootnode);
+      }
       return this;
     }
 
+    public Builder discoveryBootnodesFromUrl(final String bootnodeUrl) {
```
Comment (lucassaldanha) [inline ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java]: NIT: I'd rename `bootnodeUrl` to `bootnodesFileUrl` or `bootnodesSourceUrl`. Mostly because at a glance, the method makes it look like we are adding a single bootnode entry (like its ENR).

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java [hunk 3]
```diff
@@ -1138,17 +1171,12 @@ private Builder applyHoleskyNetworkDefaults() {
...
-              "enr:-LK4QDvXfoKH4pVoVoJx3vz0q-3nFtxYKgIacrYPuorPO-KrGlOwQOlCDEPh0e_1x9O2Ob6YWajVU6y7IjIGYOQfXkwEh2F0dG5ldHOIAAAAAACAAQCEZXRoMpDKcygcUAAQG___________gmlkgnY0gmlwhIlKy_CJc2VjcDI1NmsxoQOqgG9xgvsFBhOI6mfWosFJheJOxvVz2zlbQzMeK-S7dIN0Y3CCI4yDdWRwgiOM",
-              "enr:-Jq4QI0JCZcwDmfiuBbzjtmE_QTQVi4-jRUJko5RMq1RCjQeTXncHIoCtriXgU_FrCtl9R2AKSyHcmF0fCuS4pIL4h0BhGV0aDKQynMoHFAAEBv__________4JpZIJ2NIJpcIRBbZouiXNlY3AyNTZrMaEC8GXWOjFPp85Cpv9CY6V-CfzNPkMm0VyNNeuiFxfjg3mDdWRwgiMp",
-              "enr:-Iq4QIc297-de1P6hznMX2cIdVsQkve9BD9NUsJ7vVQa7eh5UpekA9rLid5A-yLiS3gZwOGugYZPi58x76zNs2cEQFCGAYhBJlTYgmlkgnY0gmlwhEFtmi6Jc2VjcDI1NmsxoQJDyix-IHa_mVwLBEN9NeG8I-RUjNQK_MGxk9OqRQUAtIN1ZHCCIyg",
-              "enr:-MS4QPNnPV4zZJkeytVQTm8fg3Mrtyq7l3oVy9ht4229w5OUOftE2EsXAfgxEopHavIPTzdWGchD-rXDh_eS6fdF_dsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDKcygcUAAQG___________gmlkgnY0gmlwhKfrAbmEcXVpY4IjUYlzZWNwMjU2azGhAwnM8CLwGlnZFe7XhDoC4PSYZMvWypChdu0NX9vmCGjKiHN5bmNuZXRzAIN0Y3CCI1CDdWRwgiNQ");
+          .discoveryBootnodesFromUrl("https://ephemery.dev/latest/boot_enr.txt");
```
Comment (lucassaldanha) [inline ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:1179]: What happens if this URL is down? I'd expect that if this is down, but I am manually setting bootnodes, that my node would boot fine. Is this only used if we don't pass bootnodes as parameters?

It looks to me that because `discoveryBootnodesFromUrl(x)` is eagerly evaluated, if for some reason the default url is down, our node won't start regardless of us trying to set an override via config.

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java [hunk 4]
```diff
@@ -192,6 +194,12 @@ private static void applyPreset(
   }
 
   private static InputStream loadConfigurationFile(final String source) throws IOException {
+    if (source.equals(EPHEMERY.configName())) {
```
Comment (lucassaldanha) [inline ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java:197]: Similar comment as before, this seems to make our node startup dependent on the URL being online with no possibility of overrding it.

**Review by lucassaldanha — APPROVED** [review]

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java (hunk 3 above)
Comment (rolfyone) [reply ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:1179]: basically you'd need to do 
```
network: url
p2p-discovery-bootnodes-url: url
initial-state: url
```
and then none of those defaults get loaded (because its only based on network name)

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java (hunk 4 above)
Comment (rolfyone) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java:197]: yeh same, because we loaded from --network ephemery it has a specific behaviour - previously was forced to load local resource, now forced to load url.

File: ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java [hunk 5]
```diff
@@ -192,6 +194,12 @@ private static void applyPreset(
...
+      return getConfigLoader()
+          .load(EPHEMERY_CONFIG_URL)
+          .orElseThrow(
+              () -> new FileNotFoundException("Could not load spec config from " + source));
+    }
```
[the remark this answers is not in the document]
Comment (rolfyone) [reply ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/SpecConfigLoader.java:202]: yes but its just defaults, they can still be overridden.

File: ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (rolfyone) [reply ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java:1179]: only when explicitly using the ephemery label
