### PR TITLE
Suppress multiple attestation gossiping failures logs

### LINKED ISSUE #5867: Excessive "Failed to publish attestation" messages after restart
Reported by a large user.

Teku 22.6.1 with separate validator process.

On restart the beacon node was excessively noisy with (duplicate) warnings. Presumeably there's one message for each validator due to attest. Can we improve this?

```
2022-06-29 12:25:04.029 INFO  - Slot Event  *** Slot: 215225, Block: 2fae512b4774fd86c6366cad5833112c2605a650a26d39333e30c7e5e1f772e9, Justified: 6724, Finalized: 6723, Peers: 70
2022-06-29 12:25:13.375 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.377 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.380 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.382 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.384 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.385 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.386 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.388 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.389 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.391 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.392 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.394 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.395 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.396 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.398 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.410 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.411 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.413 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.415 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.416 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.418 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.420 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.422 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.424 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.425 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.427 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.429 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.430 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.431 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.433 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.434 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.435 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.436 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.438 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.439 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.440 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.441 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:13.443 WARN  - Failed to publish attestation for slot 215226 because no peers were available on the required gossip topic
2022-06-29 12:25:16.030 INFO  - Slot Event  *** Slot: 215226, Block: 7a3b44df63c9d82d6884b609dc200ec92ece2c90ceb8d1c46ff4aa30600c6294, Justified: 6724, Finalized: 6723, Peers: 85
2022-06-29 12:25:25.055 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.056 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.060 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.062 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.063 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.064 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.066 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.067 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.068 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.238 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.240 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.242 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.244 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.247 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.249 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.250 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.251 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.253 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.256 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.260 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.262 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.266 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.269 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.270 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.273 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.274 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.277 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.278 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.280 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.282 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
2022-06-29 12:25:25.283 WARN  - Failed to publish attestation for slot 215227 because no peers were available on the required gossip topic
```

### PR DESCRIPTION
**Pull request by tbenr**
My attempt to improve log bursts.
The idea is to log failures only the first of a burst of attestations with same `Slot`, `IndexCommittee` and rootCause.

The synchronized method should not add any overhead in normal operation since it only applies to failure handling.

fixes #5867

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java [hunk 1]
```diff
@@ -63,25 +68,38 @@ public void onNewAttestation(final ValidateableAttestation validateableAttestati
...
+      return;
+    }
+    lastErroredSlot = attestationData.getSlot();
+    lastErroredCommitteeIndex = attestationData.getIndex();
+    if (Throwables.getRootCause(error) instanceof MessageAlreadySeenException) {
+      LOG.debug(
+          "Failed to publish attestation(s) for slot {} and committee index {} because the message has already been seen",
+          lastErroredSlot,
+          lastErroredCommitteeIndex);
+    } else if (Throwables.getRootCause(error) instanceof NoPeersForOutboundMessageException) {
```
Comment (tbenr) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java]: I could move the synchronized section here, after the debug for the "already seen", to reduce overhead.

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java [hunk 2]
```diff
@@ -63,25 +69,41 @@ public void onNewAttestation(final ValidateableAttestation validateableAttestati
...
+  synchronized void logWithSuppression(final Throwable error, final Attestation attestation) {
+    final AttestationData attestationData = attestation.getData();
+    final Throwable rootCause = Throwables.getRootCause(error);
+    if (attestationData.getSlot().equals(lastErroredSlot)
+        && attestationData.getIndex().equals(lastErroredCommitteeIndex)
+        && rootCause.equals(lastRootCause)) {
+      return;
+    }
+    lastErroredSlot = attestationData.getSlot();
+    lastErroredCommitteeIndex = attestationData.getIndex();
```
Comment (ajsutton) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java]: I'm slightly worried that the attestations won't always be published in order of committee index so we may wind up logging multiple warnings still.  I'd be very tempted to omit the committee index and just print the warning once per slot.  It's kind of useful to know the committee index but not particularly because you can't really do much.

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java [hunk 3]
```diff
@@ -63,25 +69,41 @@ public void onNewAttestation(final ValidateableAttestation validateableAttestati
...
               attestationPublishFailureCounter.inc();
             });
   }
 
+  synchronized void logWithSuppression(final Throwable error, final Attestation attestation) {
+    final AttestationData attestationData = attestation.getData();
+    final Throwable rootCause = Throwables.getRootCause(error);
+    if (attestationData.getSlot().equals(lastErroredSlot)
+        && attestationData.getIndex().equals(lastErroredCommitteeIndex)
+        && rootCause.equals(lastRootCause)) {
```
Comment (ajsutton) [inline networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java]: Slightly suspicious of using `.equals` on an Exception. I wonder if it would be better to just check if the root cause class is the same since we're only selecting based on the `instanceof` conditions below anyway.

Comment (ajsutton) [reply networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java]: Oh and probably worth logging at debug level instead of entirely suppressing.

**Review by ajsutton — APPROVED** [review]
LGTM. Couple of suggestions to ensure messages don't slip through that we don't need but you can take or leave those.

File: networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java (hunk 2 above)
Comment (tbenr) [reply networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/AttestationGossipManager.java]: Good point
