### PR TITLE
fixed getProposerDuties to be pre-fulu compatible

### LINKED ISSUE #10345: proposer v1 endpoint post fulu
- theres a new v2 endpoint for proposer duties which is going to do what our v1 currently does.
 - The existing v1 proposer endpoint needs to 'lie' about dependent root, and be more like electra (last epoch is dependent root, not 2 epochs ago).
 - Can still service next epoch duties with the correct root, its just the current epoch that we need to tweak dependent root for.
 - We'll want to sanity check that we're not missing proposals for the first slot of epochs post this change.
 
in this issue we should deal with the v1 change, and i'll raise another issue for implementation of the v2 endpoint.

### PR DESCRIPTION
**Pull request by rolfyone**
There's a new endpoint in ValidatorApiHandler that is called for dependent root compatibility.

With this change, the dependent root computation on the `proposers/{epoch}` endpoint will be returning the same roots as pre-fulu.

This is basically currentDependentRoot for current epoch, and HEAD root for next epoch.

Further work will be needed to introduce a v2 proposers endpoint that correctly follows the fulu dependent root calculations.

fixes #10345

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

---

> [!NOTE]
> **Medium Risk**
> Touches validator duty calculation and the public proposer-duties endpoint behavior, so incorrect epoch/root selection could cause validators or external clients to react to wrong duty roots; changes are covered by expanded unit/integration tests.
> 
> **Overview**
> Updates proposer duties handling so the v1 REST endpoint `GET /eth/v1/validator/duties/proposer/{epoch}` returns *pre-Fulu-compatible* `dependent_root` values even on Fulu networks.
> 
> This threads a new `isFuluCompatible` flag through `ValidatorApiChannel.getProposerDuties`, adds `ValidatorDataProvider.getProposerDutiesElectraDependentRoot`, and updates `ValidatorApiHandler` to (a) query the correct state slot based on both current and requested epochs and (b) compute `dependent_root` via `BlockProposalUtil.getBlockProposalDependentRoot` using either the Fulu or Phase0 util depending on compatibility mode.
> 
> Spec utilities are updated to reflect the new state-epoch-aware `BlockProposalUtil` signatures, and unit/integration tests are adjusted to validate the new dependent-root expectations across pre/post-Fulu scenarios. The changelog is updated to note the v1 proposer duties root compatibility fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f2a361a8147f3b496cbb60288979c4a18d6c16b3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: beacon/validator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java [hunk 1]
```diff
@@ -378,37 +378,38 @@ public void getProposerDuties_shouldFailForEpochTooFarAhead() {
...
+    final BeaconState state = createStateWithActiveValidators(epochStartSlot);
+    final Bytes32 headRoot = dataStructureUtil.randomBytes32();
+    when(chainDataClient.getStateAtSlotExact(epochStartSlot))
         .thenReturn(completedFuture(Optional.of(state)));
     when(chainDataClient.getCurrentEpoch()).thenReturn(EPOCH);
+    when(chainDataClient.getBestBlockRoot()).thenReturn(Optional.of(headRoot));
 
     final SafeFuture<Optional<ProposerDuties>> result =
-        validatorApiHandler.getProposerDuties(EPOCH);
+        validatorApiHandler.getProposerDuties(EPOCH, true);
```
[the remark this answers is not in the document]
Comment (rolfyone) [reply beacon/validator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java:412]: this is basically placeholder and will fall back if it needs to

File: data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/validator/GetProposerDutiesIntegrationTest.java [hunk 2]
```diff
@@ -124,8 +130,9 @@ void shouldReturnCorrectDependentRootPreFuluExtraSlots() throws IOException {
   // epoch  GENESIS | 0                   |<1>                     |  2
   // slot         0 | 1  2  3  4  5  6  7 | 8  9 10 11 12 13 14 15 | 16
   // query          |                     |                        |  ^
-  // dep          D |                     |                        |
-  // EXPECT - expect epoch 1 duties with dependent root slot 0 (GENESIS)
+  // dep            |                   D |                        |
+  // EXPECT - expect epoch 1 duties with dependent root slot 0
```
Comment (tbenr) [inline data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/validator/GetProposerDutiesIntegrationTest.java]: EXPECT - expect epoch 1 duties with dependent root slot 7 instead of 0?

File: beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java [hunk 3]
```diff
@@ -1036,10 +1044,20 @@ private ProposerDuties getProposerDutiesFromState(final BeaconState state, final
     }
     final UInt64 currentEpoch = spec.getCurrentEpoch(state);
     final boolean greaterThanCurrentEpoch = epoch.isGreaterThan(currentEpoch);
+    final BlockProposalUtil blockProposalUtil;
+    if (isFuluCompatible) {
+      blockProposalUtil = spec.atEpoch(epoch).getBlockProposalUtil();
+
```
Comment (tbenr) [inline beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java]: extra line

**Review by tbenr — APPROVED** [review]
LGTM, nits

File: data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/validator/GetProposerDutiesIntegrationTest.java (hunk 2 above)
Comment (rolfyone) [reply data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/validator/GetProposerDutiesIntegrationTest.java]: hrm yep thought i fixed them all
